### ISSUE TITLE
Projects in solution not loading. 

### ISSUE THREAD

**Issue by ghost** [zaharPonimash/AI.ComputerVision.DeepFake#2]
Hi, I tried to load the code in VS and some of the solutions did not load:

C:\AIFrameSharp\AI.Fram\Very Light\Sourse\AI.MathMod 2.0\AI.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\AIFrameSharp\AI.Fram\Very Light\Sourse\AI.MathMod 2.0\AI.csproj'.  C:\AIFrameSharp\AI.Fram\Very Light\Sourse\AI.MathMod 2.0\AI.csproj

C:\source\repos\DlibTestApp\AI.Dlib\AI.Dlib.csproj : error  : The project file could not be loaded. Could not find a part of the path 'C:\source\repos\DlibTestApp\AI.Dlib\AI.Dlib.csproj'.  C:\source\repos\DlibTestApp\AI.Dlib\AI.Dlib.csproj

Also, the app does not work with different images.

**Comment by zaharPonimash** [comment]
Hello!
This was a tutorial project, you can run it if you include projects as binaries. This (https://github.com/aiframesharp/AIFrameSharpNonCommercialRus) is the old version of our framework on which this project was written, and this(https://github.com/AIFramework/AI_Free) is a newer one.
 
 
Best regards, Ponimash Zahar.

**Comment by zaharPonimash** [comment]
Rebuilt the project and added the ability to upload your images.
Also note that although the "shape_predictor_68_face_landmarks.dat.bz2" model itself is licensed under the CC0 license, the author added the following note:
"This is trained on the ibug 300-W dataset (https://ibug.doc.ic.ac.uk/resources/facial-point-annotations/)

C. Sagonas, E. Antonakos, G, Tzimiropoulos, S. Zafeiriou, M. Pantic. 
300 faces In-the-wild challenge: Database and results. 
Image and Vision Computing (IMAVIS), Special Issue on Facial Landmark Localisation "In-The-Wild". 2016.

The license for this dataset excludes commercial use and Stefanos Zafeiriou, one of the creators of the dataset, asked me to include a note here saying that the trained model therefore can't be used in a commerical product. So you should contact a lawyer or talk to Imperial College London to find out if it's OK for you to use this model in a commercial product.

Also note that this model file is designed for use with dlib's HOG face detector. That is, it expects the bounding boxes from the face detector to be aligned a certain way, the way dlib's HOG face detector does it. It won't work as well when used with a face detector that produces differently aligned boxes, such as the CNN based mmod_human_face_detector.dat face detector."

----------------------------------------------------
Link: https://github.com/davisking/dlib-models

**Comment by ghost** [comment]
Thank you so much for fast and informative response, really appreciate it.
